var city1 = 'Karachi';
var city2 = 'Lahore';
console.log("Tests for equality and inequality with strings:");
console.log(city1 === 'Karachi');
console.log(city2 !== 'Karachi');
var word = 'Hello';
var lowerWord = word.toLowerCase();
console.log("\nTests using the lower case function:");
console.log(lowerWord === 'hello');
var num1 = 10;
var num2 = 20;
console.log("\nNumerical tests:");
console.log(num1 === 10);
console.log(num2 !== 10);
console.log(num1 < num2);
console.log(num2 > num1);
console.log(num1 >= 10);
console.log(num2 <= 20);
var a = true;
var b = false;
console.log("\nTests using 'and' and 'or' operators:");
console.log(a && b);
console.log(a || b);
var colors = ['red', 'green', 'blue'];
console.log("\nTest whether an item is in an array:");
console.log(colors.includes('green'));
console.log("\nTest whether an item is not in an array:");
console.log(!colors.includes('yellow'));
